name: pommes-dev
channels:
- conda-forge
- fico-xpress
dependencies:
- python=3.10
- pandas
- xarray
- linopy
- numpy
- pyyaml
- highspy
- h5netcdf
- notebook
- ipykernel
- ipython
- nbformat
- matplotlib
- pandoc
- pre-commit
- ruff
- pytest
- coverage
- sphinx
- nbsphinx
- sphinx-autoapi
- sphinx-rtd-theme
- pip
- pip:
  - gurobipy
  - Mosek
  - geopandas
  - plotly
  - cplex
  - seaborn


