name: pommes-env
channels:
- conda-forge
dependencies:
- python=3.13
- numpy
- pandas
- xarray
- highspy
- h5netcdf
- pyyaml
- sphinx
- nbsphinx
- pandoc
- notebook
- ipykernel
- ipython
- nbformat
- matplotlib
- pip
- pip:
  - sphinx-autoapi
  - sphinx-rtd-theme
  - linopy
